version: '3'

services:
  buying_frenzy:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 9341:9341
    volumes:
      - .:/opt/services/flaskapp/src
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data